name: EliAI
options:
  bundleIdPrefix: com.eliaigemini
  deploymentTarget:
    iOS: 17.0
targets:
  EliAI:
    type: application
    platform: iOS
    sources: [EliAI]
    info:
      path: EliAI/EliAI/Info.plist
      properties:
        UISupportedInterfaceOrientations: [UIInterfaceOrientationPortrait]
        UILaunchScreen: {}
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.eliaigemini.localai
      CURRENT_PROJECT_VERSION: 1
      MARKETING_VERSION: 1.0
      INFOPLIST_FILE: EliAI/EliAI/Info.plist
      CODE_SIGNING_ALLOWED: NO
      CODE_SIGNING_REQUIRED: NO
      SWIFT_COMPILATION_MODE: wholemodule
      OTHER_SWIFT_FLAGS:
        - -cxx-interoperability-mode=default
        - -enable-experimental-feature Macros
    dependencies:
      - package: LLM
        product: LLM
      - package: swift-syntax
        product: SwiftSyntaxMacros
      - sdk: Accelerate.framework
packages:
  LLM:
    path: Packages/LLM
  swift-syntax:
    url: https://github.com/apple/swift-syntax.git
    from: 602.0.0
