name: EliAI
options:
  bundleIdPrefix: com.eliaigemini
  deploymentTarget:
    iOS: 17.0
targets:
  EliAI:
    type: application
    platform: iOS
    sources: [EliAI]
    info:
      path: EliAI/EliAI/Info.plist
      properties:
        UISupportedInterfaceOrientations: [UIInterfaceOrientationPortrait]
        UILaunchScreen: {}
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.eliaigemini.localai
      CURRENT_PROJECT_VERSION: 1
      MARKETING_VERSION: 1.0
      INFOPLIST_FILE: EliAI/EliAI/Info.plist
      CODE_SIGNING_ALLOWED: NO
      CODE_SIGNING_REQUIRED: NO
    dependencies:
      - package: llama.cpp
packages:
  llama.cpp:
    url: https://github.com/ggerganov/llama.cpp
    branch: master
